import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Settings, Youtube, Twitter, Linkedin, Info } from "lucide-react";

export default function SettingsPage() {
  return (
    <div className="space-y-5 max-w-3xl">
      <h1 className="text-2xl font-semibold tracking-tight flex items-center gap-2">
        <Settings className="h-6 w-6 text-amber-500" />
        Settings
      </h1>

      <Card className="border-border/50">
        <CardHeader className="pb-2">
          <CardTitle className="text-sm font-medium flex items-center gap-2">
            <Youtube className="h-4 w-4 text-red-500" />
            YouTube Integration
          </CardTitle>
        </CardHeader>
        <CardContent className="space-y-2">
          <p className="text-sm text-muted-foreground">
            YouTube uploads are handled via the YouTube Data API v3 using the credentials configured in the server environment.
          </p>
          <div className="flex items-center gap-2 text-xs text-muted-foreground bg-muted/30 rounded p-2">
            <Info className="h-3 w-3 shrink-0" />
            <span>YOUTUBE_API_KEY is configured in server environment. OAuth tokens are stored in the database.</span>
          </div>
        </CardContent>
      </Card>

      <Card className="border-border/50">
        <CardHeader className="pb-2">
          <CardTitle className="text-sm font-medium flex items-center gap-2">
            <Twitter className="h-4 w-4 text-sky-400" />
            X (Twitter) Integration
          </CardTitle>
        </CardHeader>
        <CardContent className="space-y-2">
          <p className="text-sm text-muted-foreground">
            X posts are published via the X API v2 using OAuth 2.0 credentials. The system posts on behalf of the configured account.
          </p>
          <div className="flex items-center gap-2 text-xs text-muted-foreground bg-muted/30 rounded p-2">
            <Info className="h-3 w-3 shrink-0" />
            <span>X_API_KEY, X_API_SECRET, X_ACCESS_TOKEN, X_ACCESS_TOKEN_SECRET are configured in server environment.</span>
          </div>
        </CardContent>
      </Card>

      <Card className="border-border/50">
        <CardHeader className="pb-2">
          <CardTitle className="text-sm font-medium flex items-center gap-2">
            <Linkedin className="h-4 w-4 text-blue-400" />
            LinkedIn
          </CardTitle>
        </CardHeader>
        <CardContent className="space-y-2">
          <p className="text-sm text-muted-foreground">
            LinkedIn does not support direct API posting for personal profiles. All LinkedIn content is generated and copied to clipboard for manual posting.
          </p>
          <div className="flex items-center gap-2 text-xs text-amber-500/80 bg-amber-500/10 rounded p-2">
            <Info className="h-3 w-3 shrink-0" />
            <span>Use the "Copy LinkedIn Post" button in Montage Studio or the Content Calendar to copy formatted copy.</span>
          </div>
        </CardContent>
      </Card>

      <Card className="border-border/50">
        <CardHeader className="pb-2">
          <CardTitle className="text-sm font-medium flex items-center gap-2">
            <Info className="h-4 w-4 text-amber-500" />
            Content Thesis
          </CardTitle>
        </CardHeader>
        <CardContent>
          <div className="bg-amber-500/10 border border-amber-500/20 rounded-lg p-4">
            <p className="text-sm font-semibold text-amber-400 mb-2">
              Every piece of content generated by this system is framed around one claim:
            </p>
            <p className="text-base font-bold text-foreground">
              "CodexYield generates more Bitcoin than simply buying and holding Bitcoin."
            </p>
            <p className="text-xs text-muted-foreground mt-2">
              This thesis is embedded in every AI prompt: chart narrations, video scripts, metadata, X posts, LinkedIn copy, and YouTube descriptions. It cannot be overridden.
            </p>
          </div>
        </CardContent>
      </Card>
    </div>
  );
}
